### ISSUE TITLE
Add tests for JavaScript and rename repository

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/testsuite-extended#22]
# Overview

This is data and rules for a test suite, it should not be language specific.

We can definitely use features on various public CI servers to have both python and node runtimes available, either by installing as part of the CI run, or using a custom image we supply.
# Tasks
- [x] rename repository to `testsuite`
- [ ] add javascript tests

**Comment by roll** [comment]
I was thinking on the same design lately so +1

**Comment by roll** [comment]
MOVED
https://github.com/frictionlessdata/testsuite-basic/issues/1
